### ISSUE TITLE
Request for payment method discount to be displayed in the cart contents area on checkout page

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_pma#2]
The payment method discount is not displayed in the Checkout page in the cart contents area, whereas another discount (from uc_discounts) is. Could that be adjusted to show? It's already functional but this would make it perfect.
![image](https://github.com/backdrop-contrib/uc_pma/assets/54537636/2f888656-2bb2-4555-80af-00727e44abdd)

**Comment by bugfolder** [comment]
This one is going to be tricky. It wasn't implemented in the original D7 module, so we'll have to add it. 

However, the way to add it is (or would be) to override the theme for the Cart contents table (`theme_uc_cart_review_table()`), and the way this would be done is to set the `#theme` of that render element to our custom theming function, something like `uc_pma_uc_cart_review_table()`. This is, in fact, exactly what is done by the UC Discounts module, which uses the custom theming function `uc_discounts_uc_cart_review_table()`.

The problem will be that if we try this and have both UC Discounts and UC PMA enabled, they will fight over who gets to override the theme function for cart review.

The two modules do play nicely together when modifying the table that appears in the Payment method pane.

So I'll need to study this further to see what can be done.

I will note that the with both modules enabled, the Review page and final order are correct; it's just this checkout pane that is messed up.

**Comment by bugfolder** [comment]
A few more thoughts on this.

I think the inconsistency is arising in part because UC Discounts shows its discount in two places on the checkout page: in the "Cart Contents" pane, and the "Payment Methods" pane. But the UC PMA module only shows its discount in the "Payment Methods" pane, and that makes sense on its own, because that discount (or fee) is tied specifically to the payment method that is chosen.

Note, though, that since the UC Discounts discount is also shown in the "Payment Methods" pane, its presence in the "Cart Contents" pane is somewhat superfluous. In fact, I think the checkout page makes perfect sense if the UC Discounts discount is _not_ shown in "Cart Contents," like this:

![checkout](https://github.com/backdrop-contrib/uc_pma/assets/29214084/1c465a3e-afb3-4b6f-84b6-0e1b4ad4fee2)

Here, "Cart Contents" ends with the subtotal; then you have the Discount Codes pane, and finally, the discount shows up in the Payment Method pane ("Test discount," in this example), along with the UC PMA discount/fee ("Credit card fee," in this example).

So it looks like this issue would be solved by simply _not_ showing the UC Discounts discount up in "Cart Contents", leaving it to still appear in "Payment Method."

I would propose to leave UC PMA the way it is, but add a feature to UC Discounts that makes showing the discount in the Cart Contents pane optional via a checkbox in the settings. (I could also imagine people wanting to not show the same discount twice on the checkout page irrespective of UC PMA's presence or absence.)

@nattywebdev, what's your reaction to my analysis and proposal?

**Comment by nattywebdev** [comment]
@bugfolder I completely agree with your analysis and proposal. My use case here is for a membership subscription, paid once a year and your proposal would fit nicely.

So the Cart Contents would show only what had been ordered and not include display of any discounts. This is consistent with the display on the Review page, where discounts are currently shown only in the Payment Method table and not in the Cart Contents table.

Do you need me to raise that as an issue on the uc_discounts issue list?
https://github.com/backdrop-contrib/uc_discounts/issues

**Comment by bugfolder** [comment]
Yes, go ahead and raise the issue, and I'll get it implemented in a new release in the next day or so.

**Comment by nattywebdev** [comment]
Done: https://github.com/backdrop-contrib/uc_discounts/issues/24
Thanks for your enormous help here, @bugfolder !
